name: task_manager
description: "A new Flutter task manager project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons fonts to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  pin_code_fields: ^8.0.1
  cached_network_image: ^3.3.1
  http: ^1.2.1
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  get: ^4.6.6
  intl: ^0.18.0


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/planning.png"
  min_sdk_android: 21



  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/img/



  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see

  # example:
  fonts:
     - family: Roboto
       fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
